CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone_number" varchar,
  "document_type" varchar,
  "document_number" varchar UNIQUE NOT NULL,
  "user_type" varchar,
  "created_at" datetime,
  "updated_at" datetime,
  "deleted_at" datetime
);

CREATE TABLE "Asset" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "placa" varchar UNIQUE NOT NULL,
  "empresa_propietaria" varchar,
  "marca" varchar,
  "modelo" varchar,
  "año" int,
  "estado" varchar,
  "descripcion" text,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "Auction" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id" int NOT NULL,
  "fecha_inicio" datetime,
  "fecha_fin" datetime,
  "fecha_limite_pago" datetime,
  "estado" varchar,
  "id_offerWin" int,
  "finished_at" datetime,
  "pago_validado" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "Offer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" int NOT NULL,
  "user_id" int NOT NULL,
  "monto_oferta" decimal NOT NULL,
  "fecha_oferta" datetime,
  "posicion_ranking" int,
  "fecha_asignacion_ganador" datetime,
  "estado" varchar
);

CREATE TABLE "Guarantee_Payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "auction_id" int NOT NULL,
  "offer_id" int NOT NULL,
  "monto_garantia" decimal NOT NULL,
  "tipo_pago" varchar,
  "numero_cuenta_origen" varchar,
  "voucher_url" varchar,
  "comentarios" text,
  "estado" varchar,
  "fecha_pago" datetime,
  "fecha_validacion" datetime,
  "billing_document_type" varchar,
  "billing_name" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "User_Balance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "saldo_total" decimal NOT NULL,
  "saldo_retenido" decimal,
  "saldo_aplicado" decimal,
  "saldo_enReembolso" decimal,
  "saldo_penalizado" decimal,
  "updated_at" datetime
);

CREATE TABLE "Movement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "tipo_movimiento" varchar,
  "monto" decimal,
  "descripcion" text,
  "reference_type" varchar,
  "reference_id" int,
  "created_at" datetime
);

CREATE TABLE "Refund" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "monto_solicitado" decimal,
  "tipo_reembolso" varchar,
  "estado" varchar,
  "fecha_solicitud" datetime,
  "fecha_respuesta_empresa" datetime,
  "fecha_procesamiento" datetime,
  "motivo" text,
  "created_at" datetime,
  "updated_at" datetime
);

ALTER TABLE "Auction" ADD FOREIGN KEY ("asset_id") REFERENCES "Asset" ("id");

ALTER TABLE "Offer" ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("id");

ALTER TABLE "Offer" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Guarantee_Payment" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Guarantee_Payment" ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("id");

ALTER TABLE "Guarantee_Payment" ADD FOREIGN KEY ("offer_id") REFERENCES "Offer" ("id");

ALTER TABLE "User_Balance" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Movement" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Refund" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");
